version: '3.8'
services:
  rpms-service:
    container_name: rpms-service
    build:
      context: rpms-service  # Thay đổi thư mục build nếu cần
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/RPMSDb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    healthcheck:
      test: "exit 0"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: RPMSDb  # Sửa tên DB ở đây
    healthcheck:
      test: "exit 0"
